import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { analyse } from '../../src/core/engine/engine.js';
import { renderMarkdown } from '../../src/core/render/markdown.js';
import { SCENARIOS } from '../fixtures/scenarios.js';

const EXAMPLES_DIR = path.resolve(import.meta.dirname, '../../docs/examples');
const UPDATE = process.env['UPDATE_GOLDEN'] === '1';

/**
 * Golden tests over the rendered comment.
 *
 * The files in `docs/examples` are the documentation *and* the expectation.
 * Anything that changes the report — a rule, a weight, a word — shows up here
 * as a reviewable diff instead of quietly changing what users see.
 *
 * Run `npm run demo` to regenerate them.
 */
describe('rendered reports', () => {
  for (const entry of SCENARIOS) {
    it(`matches the golden report for ${entry.name}`, async () => {
      const report = analyse(entry.build());
      const rendered = [
        `<!-- Generated by \`npm run demo\`. Scenario: ${entry.name} — ${entry.description} -->`,
        '',
        renderMarkdown(report),
      ].join('\n');

      const file = path.join(EXAMPLES_DIR, `${entry.name}.md`);

      if (UPDATE) {
        await mkdir(EXAMPLES_DIR, { recursive: true });
        await writeFile(file, rendered, 'utf8');
        return;
      }

      const expected = await readFile(file, 'utf8').catch(() => null);
      expect(expected, `missing golden file ${file}; run "npm run demo"`).not.toBeNull();
      expect(rendered).toBe(expected);
    });
  }
});
